name: country_pickers_v2
description: Countries, codes, flags and several way of picking them at your service...one widget away...
version: 3.0.1
homepage: https://github.com/JibuVarghese/country_pickers

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/